/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finansaku2;

/**
 *
 * @author odygunadiksa
 */
public class berandaSaku extends javax.swing.JFrame {

    /**
     * Creates new form berandaSaku
     */
    public berandaSaku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContent = new javax.swing.JPanel();
        greetContainer = new javax.swing.JPanel();
        greetText = new javax.swing.JLabel();
        usernameText = new javax.swing.JLabel();
        greetDesc = new javax.swing.JLabel();
        greetImage = new javax.swing.JLabel();
        riwayat = new javax.swing.JLabel();
        catat = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        catatBox = new javax.swing.JPanel();
        catatDesc = new javax.swing.JLabel();
        catatLogo = new javax.swing.JLabel();
        pengeluaranBox = new javax.swing.JPanel();
        pengeluaranText = new javax.swing.JLabel();
        pengeluaranRp = new javax.swing.JLabel();
        pengeluaranTotal = new javax.swing.JLabel();
        pemasukkanBox = new javax.swing.JPanel();
        pemasukkanText = new javax.swing.JLabel();
        pemasukkanRp = new javax.swing.JLabel();
        pemasukkanTotal = new javax.swing.JLabel();
        copyrightText = new javax.swing.JLabel();
        Day = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Sidebar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        dashboardOption = new javax.swing.JPanel();
        dashboardText = new javax.swing.JLabel();
        dashboardIcon = new javax.swing.JLabel();
        catatOption = new javax.swing.JPanel();
        catatText = new javax.swing.JLabel();
        catatIcon = new javax.swing.JLabel();
        laporanOption = new javax.swing.JPanel();
        laporanText = new javax.swing.JLabel();
        laporanIcon = new javax.swing.JLabel();
        riwayatOption = new javax.swing.JPanel();
        riwayatText = new javax.swing.JLabel();
        riwayatIcon = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        userPhoto = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainContent.setBackground(new java.awt.Color(233, 233, 243));

        greetContainer.setBackground(new java.awt.Color(145, 149, 246));
        greetContainer.setPreferredSize(new java.awt.Dimension(940, 334));

        greetText.setFont(new java.awt.Font("PT Sans", 0, 36)); // NOI18N
        greetText.setForeground(new java.awt.Color(255, 255, 255));
        greetText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetText.setText("Hai,");

        usernameText.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        usernameText.setForeground(new java.awt.Color(255, 255, 255));
        usernameText.setText("Sutha!");

        greetDesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        greetDesc.setForeground(new java.awt.Color(242, 242, 242));
        greetDesc.setText("Mau melakukan apa hari ini?");

        greetImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Picsart_24-03-04_15-29-24-853 1.png"))); // NOI18N

        riwayat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        riwayat.setForeground(new java.awt.Color(255, 255, 255));
        riwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/degree fix size.png"))); // NOI18N
        riwayat.setText("Cek Riwayat Transaksi");

        catat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        catat.setForeground(new java.awt.Color(255, 255, 255));
        catat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/degree fix size.png"))); // NOI18N
        catat.setText("Catat Transaksi Baru");

        laporan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        laporan.setForeground(new java.awt.Color(255, 255, 255));
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/degree fix size.png"))); // NOI18N
        laporan.setText("Laporan Transaksi");

        javax.swing.GroupLayout greetContainerLayout = new javax.swing.GroupLayout(greetContainer);
        greetContainer.setLayout(greetContainerLayout);
        greetContainerLayout.setHorizontalGroup(
            greetContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greetContainerLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(greetContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(greetContainerLayout.createSequentialGroup()
                        .addComponent(greetText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameText))
                    .addComponent(greetDesc)
                    .addComponent(riwayat)
                    .addGroup(greetContainerLayout.createSequentialGroup()
                        .addComponent(catat)
                        .addGap(36, 36, 36)
                        .addComponent(laporan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(greetImage)
                .addGap(52, 52, 52))
        );
        greetContainerLayout.setVerticalGroup(
            greetContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greetContainerLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(greetContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greetText)
                    .addComponent(usernameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greetDesc)
                .addGap(44, 44, 44)
                .addGroup(greetContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catat)
                    .addComponent(laporan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(riwayat)
                .addContainerGap())
            .addComponent(greetImage, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        dashboard.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        dashboard.setText("Dashboard");

        catatBox.setBackground(new java.awt.Color(255, 255, 255));
        catatBox.setPreferredSize(new java.awt.Dimension(301, 226));

        catatDesc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        catatDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catatDesc.setText("Catat Transaksi");

        catatLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catatLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/plus icon fix size (1).png"))); // NOI18N

        javax.swing.GroupLayout catatBoxLayout = new javax.swing.GroupLayout(catatBox);
        catatBox.setLayout(catatBoxLayout);
        catatBoxLayout.setHorizontalGroup(
            catatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catatBoxLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(catatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(catatDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(catatLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        catatBoxLayout.setVerticalGroup(
            catatBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catatBoxLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(catatDesc)
                .addGap(26, 26, 26)
                .addComponent(catatLogo)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pengeluaranBox.setBackground(new java.awt.Color(255, 126, 165));
        pengeluaranBox.setPreferredSize(new java.awt.Dimension(301, 226));

        pengeluaranText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pengeluaranText.setForeground(new java.awt.Color(255, 255, 255));
        pengeluaranText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengeluaranText.setText("Total Pengeluaran");

        pengeluaranRp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pengeluaranRp.setForeground(new java.awt.Color(255, 255, 255));
        pengeluaranRp.setText("Rp");

        pengeluaranTotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pengeluaranTotal.setForeground(new java.awt.Color(255, 255, 255));
        pengeluaranTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pengeluaranTotal.setText("0");

        javax.swing.GroupLayout pengeluaranBoxLayout = new javax.swing.GroupLayout(pengeluaranBox);
        pengeluaranBox.setLayout(pengeluaranBoxLayout);
        pengeluaranBoxLayout.setHorizontalGroup(
            pengeluaranBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengeluaranBoxLayout.createSequentialGroup()
                .addGroup(pengeluaranBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pengeluaranBoxLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(pengeluaranRp))
                    .addGroup(pengeluaranBoxLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pengeluaranBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pengeluaranTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pengeluaranText, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pengeluaranBoxLayout.setVerticalGroup(
            pengeluaranBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengeluaranBoxLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pengeluaranText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pengeluaranRp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pengeluaranTotal)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pemasukkanBox.setBackground(new java.awt.Color(167, 201, 87));

        pemasukkanText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pemasukkanText.setForeground(new java.awt.Color(255, 255, 255));
        pemasukkanText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pemasukkanText.setText("Total Pemasukkan");

        pemasukkanRp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pemasukkanRp.setForeground(new java.awt.Color(255, 255, 255));
        pemasukkanRp.setText("Rp");

        pemasukkanTotal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pemasukkanTotal.setForeground(new java.awt.Color(255, 255, 255));
        pemasukkanTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pemasukkanTotal.setText("0");

        javax.swing.GroupLayout pemasukkanBoxLayout = new javax.swing.GroupLayout(pemasukkanBox);
        pemasukkanBox.setLayout(pemasukkanBoxLayout);
        pemasukkanBoxLayout.setHorizontalGroup(
            pemasukkanBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemasukkanBoxLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pemasukkanBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pemasukkanBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pemasukkanBoxLayout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(pemasukkanRp))
                        .addComponent(pemasukkanTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pemasukkanText, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pemasukkanBoxLayout.setVerticalGroup(
            pemasukkanBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemasukkanBoxLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(pemasukkanText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pemasukkanRp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pemasukkanTotal)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        copyrightText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightText.setText("Copyright © FinanSaku | Created by Kelompok 2.");
        copyrightText.setToolTipText("");

        Day.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Day.setText("Senin,");

        Date.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Date.setText("9 Maret 2024");

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(copyrightText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainContentLayout.createSequentialGroup()
                            .addComponent(catatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pengeluaranBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pemasukkanBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(mainContentLayout.createSequentialGroup()
                            .addComponent(dashboard)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Day)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Date))
                        .addComponent(greetContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Day)
                        .addComponent(Date))
                    .addComponent(dashboard))
                .addGap(18, 18, 18)
                .addComponent(greetContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengeluaranBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pemasukkanBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(copyrightText)
                .addContainerGap())
        );

        getContentPane().add(mainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 980, 770));

        Sidebar.setBackground(new java.awt.Color(33, 25, 81));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/FinanSaku_1_-removebg-preview 1 (1).png"))); // NOI18N

        dashboardOption.setBackground(new java.awt.Color(55, 48, 98));
        dashboardOption.setForeground(new java.awt.Color(255, 255, 255));

        dashboardText.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        dashboardText.setForeground(new java.awt.Color(255, 255, 255));
        dashboardText.setText("Dashboard");

        dashboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 3.png"))); // NOI18N

        javax.swing.GroupLayout dashboardOptionLayout = new javax.swing.GroupLayout(dashboardOption);
        dashboardOption.setLayout(dashboardOptionLayout);
        dashboardOptionLayout.setHorizontalGroup(
            dashboardOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardOptionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(dashboardIcon)
                .addGap(27, 27, 27)
                .addComponent(dashboardText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardOptionLayout.setVerticalGroup(
            dashboardOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardOptionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dashboardText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(dashboardIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        catatOption.setBackground(new java.awt.Color(33, 25, 81));
        catatOption.setForeground(new java.awt.Color(255, 255, 255));

        catatText.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        catatText.setForeground(new java.awt.Color(166, 163, 185));
        catatText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catatText.setText("Catat Transaksi");

        catatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 5(1).png"))); // NOI18N

        javax.swing.GroupLayout catatOptionLayout = new javax.swing.GroupLayout(catatOption);
        catatOption.setLayout(catatOptionLayout);
        catatOptionLayout.setHorizontalGroup(
            catatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catatOptionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(catatIcon)
                .addGap(27, 27, 27)
                .addComponent(catatText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        catatOptionLayout.setVerticalGroup(
            catatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catatIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(catatText, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        laporanOption.setBackground(new java.awt.Color(33, 25, 81));
        laporanOption.setForeground(new java.awt.Color(255, 255, 255));

        laporanText.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        laporanText.setForeground(new java.awt.Color(166, 163, 185));
        laporanText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laporanText.setText("Laporan");

        laporanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 5(2).png"))); // NOI18N

        javax.swing.GroupLayout laporanOptionLayout = new javax.swing.GroupLayout(laporanOption);
        laporanOption.setLayout(laporanOptionLayout);
        laporanOptionLayout.setHorizontalGroup(
            laporanOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanOptionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(laporanIcon)
                .addGap(27, 27, 27)
                .addComponent(laporanText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        laporanOptionLayout.setVerticalGroup(
            laporanOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laporanIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporanText, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        riwayatOption.setBackground(new java.awt.Color(33, 25, 81));
        riwayatOption.setForeground(new java.awt.Color(255, 255, 255));

        riwayatText.setBackground(new java.awt.Color(166, 163, 185));
        riwayatText.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        riwayatText.setForeground(new java.awt.Color(166, 163, 185));
        riwayatText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        riwayatText.setText("Riwayat Transaksi");
        riwayatText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatTextMouseClicked(evt);
            }
        });

        riwayatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 5.png"))); // NOI18N

        javax.swing.GroupLayout riwayatOptionLayout = new javax.swing.GroupLayout(riwayatOption);
        riwayatOption.setLayout(riwayatOptionLayout);
        riwayatOptionLayout.setHorizontalGroup(
            riwayatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, riwayatOptionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(riwayatIcon)
                .addGap(27, 27, 27)
                .addComponent(riwayatText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        riwayatOptionLayout.setVerticalGroup(
            riwayatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(riwayatText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(riwayatIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        logout.setBackground(new java.awt.Color(55, 48, 98));

        userPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Ellipse 1.png"))); // NOI18N
        userPhoto.setText(" ");

        username.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Sutha");

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(userPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutIcon)
                .addGap(21, 21, 21))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(userPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(riwayatOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarLayout.createSequentialGroup()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SidebarLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(catatOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporanOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(dashboardOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(riwayatOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catatOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 770));

        setSize(new java.awt.Dimension(1382, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void riwayatTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(berandaSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(berandaSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(berandaSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(berandaSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new berandaSaku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Day;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JLabel catat;
    private javax.swing.JPanel catatBox;
    private javax.swing.JLabel catatDesc;
    private javax.swing.JLabel catatIcon;
    private javax.swing.JLabel catatLogo;
    private javax.swing.JPanel catatOption;
    private javax.swing.JLabel catatText;
    private javax.swing.JLabel copyrightText;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel dashboardIcon;
    private javax.swing.JPanel dashboardOption;
    private javax.swing.JLabel dashboardText;
    private javax.swing.JPanel greetContainer;
    private javax.swing.JLabel greetDesc;
    private javax.swing.JLabel greetImage;
    private javax.swing.JLabel greetText;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel laporanIcon;
    private javax.swing.JPanel laporanOption;
    private javax.swing.JLabel laporanText;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel pemasukkanBox;
    private javax.swing.JLabel pemasukkanRp;
    private javax.swing.JLabel pemasukkanText;
    private javax.swing.JLabel pemasukkanTotal;
    private javax.swing.JPanel pengeluaranBox;
    private javax.swing.JLabel pengeluaranRp;
    private javax.swing.JLabel pengeluaranText;
    private javax.swing.JLabel pengeluaranTotal;
    private javax.swing.JLabel riwayat;
    private javax.swing.JLabel riwayatIcon;
    private javax.swing.JPanel riwayatOption;
    private javax.swing.JLabel riwayatText;
    private javax.swing.JLabel userPhoto;
    private javax.swing.JLabel username;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
