/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finansaku2;

/**
 *
 * @author odygunadiksa
 */
public class catatSaku extends javax.swing.JFrame {

    /**
     * Creates new form berandaSaku
     */
    public catatSaku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContent = new javax.swing.JPanel();
        catatTransaksi = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        catatContainer = new javax.swing.JPanel();
        kategori = new javax.swing.JLabel();
        kategoriPil = new javax.swing.JComboBox();
        nominal = new javax.swing.JLabel();
        nominalTf = new javax.swing.JFormattedTextField();
        deskripsi = new javax.swing.JLabel();
        datePil = new javax.swing.JFormattedTextField();
        dateText = new javax.swing.JLabel();
        deskripsiTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buatButton = new javax.swing.JPanel();
        buatText = new javax.swing.JLabel();
        hapusButton = new javax.swing.JPanel();
        hapusText = new javax.swing.JLabel();
        Sidebar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        dashboardOption = new javax.swing.JPanel();
        dashboardText = new javax.swing.JLabel();
        dashboardIcon = new javax.swing.JLabel();
        catatOption = new javax.swing.JPanel();
        catatText = new javax.swing.JLabel();
        catatIcon = new javax.swing.JLabel();
        laporanOption = new javax.swing.JPanel();
        laporanText = new javax.swing.JLabel();
        laporanIcon = new javax.swing.JLabel();
        riwayatOption = new javax.swing.JPanel();
        riwayatText = new javax.swing.JLabel();
        riwayatIcon = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        userPhoto = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainContent.setBackground(new java.awt.Color(233, 233, 243));

        catatTransaksi.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        catatTransaksi.setText("Catat Transaksi");

        day.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        day.setText("Senin,");

        date.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        date.setText("9 Maret 2024");

        catatContainer.setBackground(new java.awt.Color(255, 255, 255));

        kategori.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kategori.setText("Kategori");

        kategoriPil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kategoriPil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pemasukkan", "Pengeluaran" }));

        nominal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nominal.setText("Nominal");

        nominalTf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00;(#,##0.00)"))));
        nominalTf.setPreferredSize(new java.awt.Dimension(105, 23));

        deskripsi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deskripsi.setText("Deskripsi");

        datePil.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        datePil.setText("Mar 9, 2024");
        datePil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePilActionPerformed(evt);
            }
        });

        dateText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateText.setText("Tanggal");

        deskripsiTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskripsiTfActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/catatImg.png"))); // NOI18N

        javax.swing.GroupLayout catatContainerLayout = new javax.swing.GroupLayout(catatContainer);
        catatContainer.setLayout(catatContainerLayout);
        catatContainerLayout.setHorizontalGroup(
            catatContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catatContainerLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(catatContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kategori)
                    .addComponent(deskripsi)
                    .addComponent(nominal)
                    .addComponent(dateText)
                    .addComponent(nominalTf, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addComponent(datePil)
                    .addComponent(kategoriPil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deskripsiTf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );
        catatContainerLayout.setVerticalGroup(
            catatContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catatContainerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(kategori)
                .addGap(18, 18, 18)
                .addComponent(kategoriPil, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(dateText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(datePil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(nominal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nominalTf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(deskripsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deskripsiTf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(catatContainerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buatButton.setBackground(new java.awt.Color(167, 201, 87));

        buatText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buatText.setForeground(new java.awt.Color(255, 255, 255));
        buatText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buatText.setText("Buat");

        javax.swing.GroupLayout buatButtonLayout = new javax.swing.GroupLayout(buatButton);
        buatButton.setLayout(buatButtonLayout);
        buatButtonLayout.setHorizontalGroup(
            buatButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buatButtonLayout.createSequentialGroup()
                .addComponent(buatText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        buatButtonLayout.setVerticalGroup(
            buatButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buatText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hapusButton.setBackground(new java.awt.Color(255, 126, 165));

        hapusText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hapusText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hapusText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/delete 1.png"))); // NOI18N

        javax.swing.GroupLayout hapusButtonLayout = new javax.swing.GroupLayout(hapusButton);
        hapusButton.setLayout(hapusButtonLayout);
        hapusButtonLayout.setHorizontalGroup(
            hapusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hapusText, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        hapusButtonLayout.setVerticalGroup(
            hapusButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hapusText, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainContentLayout.createSequentialGroup()
                        .addComponent(buatButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainContentLayout.createSequentialGroup()
                        .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(catatContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainContentLayout.createSequentialGroup()
                                .addComponent(catatTransaksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 725, Short.MAX_VALUE)
                                .addComponent(day)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date)))
                        .addGap(20, 20, 20))))
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catatTransaksi)
                    .addComponent(day)
                    .addComponent(date))
                .addGap(18, 18, 18)
                .addComponent(catatContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        getContentPane().add(mainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 980, 770));

        Sidebar.setBackground(new java.awt.Color(33, 25, 81));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/FinanSaku_1_-removebg-preview 1 (1).png"))); // NOI18N

        dashboardOption.setBackground(new java.awt.Color(33, 25, 81));
        dashboardOption.setForeground(new java.awt.Color(255, 255, 255));

        dashboardText.setBackground(new java.awt.Color(166, 163, 185));
        dashboardText.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        dashboardText.setForeground(new java.awt.Color(166, 163, 185));
        dashboardText.setText("Dashboard");

        dashboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/dashboardIcon.png"))); // NOI18N

        javax.swing.GroupLayout dashboardOptionLayout = new javax.swing.GroupLayout(dashboardOption);
        dashboardOption.setLayout(dashboardOptionLayout);
        dashboardOptionLayout.setHorizontalGroup(
            dashboardOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardOptionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(dashboardIcon)
                .addGap(27, 27, 27)
                .addComponent(dashboardText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardOptionLayout.setVerticalGroup(
            dashboardOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardOptionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dashboardText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(dashboardIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        catatOption.setBackground(new java.awt.Color(55, 48, 98));
        catatOption.setForeground(new java.awt.Color(255, 255, 255));

        catatText.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        catatText.setForeground(new java.awt.Color(255, 255, 255));
        catatText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catatText.setText("Catat Transaksi");

        catatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/add fixed size.png"))); // NOI18N

        javax.swing.GroupLayout catatOptionLayout = new javax.swing.GroupLayout(catatOption);
        catatOption.setLayout(catatOptionLayout);
        catatOptionLayout.setHorizontalGroup(
            catatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catatOptionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(catatIcon)
                .addGap(27, 27, 27)
                .addComponent(catatText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        catatOptionLayout.setVerticalGroup(
            catatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catatIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(catatText, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        laporanOption.setBackground(new java.awt.Color(33, 25, 81));
        laporanOption.setForeground(new java.awt.Color(255, 255, 255));

        laporanText.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        laporanText.setForeground(new java.awt.Color(166, 163, 185));
        laporanText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laporanText.setText("Laporan");

        laporanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 5(2).png"))); // NOI18N

        javax.swing.GroupLayout laporanOptionLayout = new javax.swing.GroupLayout(laporanOption);
        laporanOption.setLayout(laporanOptionLayout);
        laporanOptionLayout.setHorizontalGroup(
            laporanOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanOptionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(laporanIcon)
                .addGap(27, 27, 27)
                .addComponent(laporanText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        laporanOptionLayout.setVerticalGroup(
            laporanOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laporanIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporanText, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        riwayatOption.setBackground(new java.awt.Color(33, 25, 81));
        riwayatOption.setForeground(new java.awt.Color(255, 255, 255));

        riwayatText.setBackground(new java.awt.Color(166, 163, 185));
        riwayatText.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        riwayatText.setForeground(new java.awt.Color(166, 163, 185));
        riwayatText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        riwayatText.setText("Riwayat Transaksi");
        riwayatText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatTextMouseClicked(evt);
            }
        });

        riwayatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 5.png"))); // NOI18N

        javax.swing.GroupLayout riwayatOptionLayout = new javax.swing.GroupLayout(riwayatOption);
        riwayatOption.setLayout(riwayatOptionLayout);
        riwayatOptionLayout.setHorizontalGroup(
            riwayatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, riwayatOptionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(riwayatIcon)
                .addGap(27, 27, 27)
                .addComponent(riwayatText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        riwayatOptionLayout.setVerticalGroup(
            riwayatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(riwayatText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(riwayatIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        logout.setBackground(new java.awt.Color(55, 48, 98));

        userPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Ellipse 1.png"))); // NOI18N
        userPhoto.setText(" ");

        username.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Sutha");

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(userPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutIcon)
                .addGap(21, 21, 21))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(userPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(riwayatOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarLayout.createSequentialGroup()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SidebarLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(catatOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporanOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(dashboardOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(riwayatOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catatOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 770));

        setSize(new java.awt.Dimension(1382, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void riwayatTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatTextMouseClicked

    private void datePilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datePilActionPerformed

    private void deskripsiTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskripsiTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deskripsiTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catatSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catatSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catatSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catatSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catatSaku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel buatButton;
    private javax.swing.JLabel buatText;
    private javax.swing.JPanel catatContainer;
    private javax.swing.JLabel catatIcon;
    private javax.swing.JPanel catatOption;
    private javax.swing.JLabel catatText;
    private javax.swing.JLabel catatTransaksi;
    private javax.swing.JLabel dashboardIcon;
    private javax.swing.JPanel dashboardOption;
    private javax.swing.JLabel dashboardText;
    private javax.swing.JLabel date;
    private javax.swing.JFormattedTextField datePil;
    private javax.swing.JLabel dateText;
    private javax.swing.JLabel day;
    private javax.swing.JLabel deskripsi;
    private javax.swing.JTextField deskripsiTf;
    private javax.swing.JPanel hapusButton;
    private javax.swing.JLabel hapusText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kategori;
    private javax.swing.JComboBox kategoriPil;
    private javax.swing.JLabel laporanIcon;
    private javax.swing.JPanel laporanOption;
    private javax.swing.JLabel laporanText;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JPanel mainContent;
    private javax.swing.JLabel nominal;
    private javax.swing.JFormattedTextField nominalTf;
    private javax.swing.JLabel riwayatIcon;
    private javax.swing.JPanel riwayatOption;
    private javax.swing.JLabel riwayatText;
    private javax.swing.JLabel userPhoto;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
