/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finansaku2;

/**
 *
 * @author odygunadiksa
 */
public class laporanSaku extends javax.swing.JFrame {

    /**
     * Creates new form berandaSaku
     */
    public laporanSaku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContent = new javax.swing.JPanel();
        editContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        totalKeluarText = new javax.swing.JLabel();
        totalTsText = new javax.swing.JLabel();
        totalMasukText = new javax.swing.JLabel();
        totalKeluarNumber = new javax.swing.JLabel();
        totalTsNumber = new javax.swing.JLabel();
        totalMasukNumber = new javax.swing.JLabel();
        greetDesc = new javax.swing.JLabel();
        usernameText = new javax.swing.JLabel();
        greetText = new javax.swing.JLabel();
        editContainer19 = new javax.swing.JPanel();
        tableContainer = new javax.swing.JScrollPane();
        transaksiTable = new javax.swing.JTable();
        riwayat1 = new javax.swing.JLabel();
        cetakButton = new javax.swing.JPanel();
        cetakText = new javax.swing.JLabel();
        Sidebar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        dashboardOption = new javax.swing.JPanel();
        dashboardText = new javax.swing.JLabel();
        dashboardIcon = new javax.swing.JLabel();
        catatOption = new javax.swing.JPanel();
        catatText = new javax.swing.JLabel();
        catatIcon = new javax.swing.JLabel();
        laporanOption = new javax.swing.JPanel();
        laporanText = new javax.swing.JLabel();
        laporanIcon = new javax.swing.JLabel();
        riwayatOption = new javax.swing.JPanel();
        riwayatText = new javax.swing.JLabel();
        riwayatIcon = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        userPhoto = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainContent.setBackground(new java.awt.Color(233, 233, 243));

        editContainer.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setPreferredSize(new java.awt.Dimension(3, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(249, 249, 249));
        jPanel7.setPreferredSize(new java.awt.Dimension(3, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        totalKeluarText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalKeluarText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalKeluarText.setText("Total Pengeluaran");

        totalTsText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalTsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalTsText.setText("Total Transaksi");

        totalMasukText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalMasukText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalMasukText.setText("Total Pemasukkan");

        totalKeluarNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalKeluarNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalKeluarNumber.setText("0");

        totalTsNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalTsNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalTsNumber.setText("0");

        totalMasukNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalMasukNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalMasukNumber.setText("0");

        javax.swing.GroupLayout editContainerLayout = new javax.swing.GroupLayout(editContainer);
        editContainer.setLayout(editContainerLayout);
        editContainerLayout.setHorizontalGroup(
            editContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalTsText, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(totalMasukText, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(editContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editContainerLayout.createSequentialGroup()
                        .addComponent(totalKeluarText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editContainerLayout.createSequentialGroup()
                        .addComponent(totalKeluarNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(editContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editContainerLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(totalTsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(443, Short.MAX_VALUE)))
            .addGroup(editContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editContainerLayout.createSequentialGroup()
                    .addGap(215, 215, 215)
                    .addComponent(totalMasukNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );
        editContainerLayout.setVerticalGroup(
            editContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editContainerLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(editContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalMasukText)
                    .addComponent(totalTsText)
                    .addGroup(editContainerLayout.createSequentialGroup()
                        .addComponent(totalKeluarText)
                        .addGap(27, 27, 27)
                        .addComponent(totalKeluarNumber))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(editContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editContainerLayout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addComponent(totalTsNumber)
                    .addGap(53, 53, 53)))
            .addGroup(editContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editContainerLayout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addComponent(totalMasukNumber)
                    .addGap(53, 53, 53)))
        );

        greetDesc.setBackground(new java.awt.Color(0, 0, 0));
        greetDesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        greetDesc.setText("Ini adalah rekapan hasil catatan kamu selama sebulan");

        usernameText.setBackground(new java.awt.Color(0, 0, 0));
        usernameText.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        usernameText.setText("Sutha!");

        greetText.setBackground(new java.awt.Color(0, 0, 0));
        greetText.setFont(new java.awt.Font("PT Sans", 0, 36)); // NOI18N
        greetText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetText.setText("Hai,");

        editContainer19.setBackground(new java.awt.Color(33, 25, 81));

        javax.swing.GroupLayout editContainer19Layout = new javax.swing.GroupLayout(editContainer19);
        editContainer19.setLayout(editContainer19Layout);
        editContainer19Layout.setHorizontalGroup(
            editContainer19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        editContainer19Layout.setVerticalGroup(
            editContainer19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        transaksiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kategori", "Tanggal", "Nominal", "Deskripsi"
            }
        ));
        tableContainer.setViewportView(transaksiTable);

        riwayat1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        riwayat1.setText("Riwayat Transaksi ( 1 bulan terakhir )");
        riwayat1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                riwayat1ComponentRemoved(evt);
            }
        });

        cetakButton.setBackground(new java.awt.Color(167, 201, 87));

        cetakText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cetakText.setForeground(new java.awt.Color(255, 255, 255));
        cetakText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cetakText.setText("Cetak");

        javax.swing.GroupLayout cetakButtonLayout = new javax.swing.GroupLayout(cetakButton);
        cetakButton.setLayout(cetakButtonLayout);
        cetakButtonLayout.setHorizontalGroup(
            cetakButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetakButtonLayout.createSequentialGroup()
                .addComponent(cetakText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cetakButtonLayout.setVerticalGroup(
            cetakButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cetakButtonLayout.createSequentialGroup()
                .addComponent(cetakText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainContentLayout = new javax.swing.GroupLayout(mainContent);
        mainContent.setLayout(mainContentLayout);
        mainContentLayout.setHorizontalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cetakButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(riwayat1)
                    .addGroup(mainContentLayout.createSequentialGroup()
                        .addComponent(greetText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameText))
                    .addComponent(greetDesc)
                    .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(mainContentLayout.createSequentialGroup()
                            .addComponent(editContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(editContainer19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tableContainer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        mainContentLayout.setVerticalGroup(
            mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainContentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greetText)
                    .addComponent(usernameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greetDesc)
                .addGap(18, 18, 18)
                .addGroup(mainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editContainer19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(riwayat1)
                .addGap(18, 18, 18)
                .addComponent(tableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cetakButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        getContentPane().add(mainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 980, 770));

        Sidebar.setBackground(new java.awt.Color(33, 25, 81));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/FinanSaku_1_-removebg-preview 1 (1).png"))); // NOI18N

        dashboardOption.setBackground(new java.awt.Color(33, 25, 81));
        dashboardOption.setForeground(new java.awt.Color(255, 255, 255));

        dashboardText.setBackground(new java.awt.Color(166, 163, 185));
        dashboardText.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        dashboardText.setForeground(new java.awt.Color(166, 163, 185));
        dashboardText.setText("Dashboard");

        dashboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/dashboardIcon.png"))); // NOI18N

        javax.swing.GroupLayout dashboardOptionLayout = new javax.swing.GroupLayout(dashboardOption);
        dashboardOption.setLayout(dashboardOptionLayout);
        dashboardOptionLayout.setHorizontalGroup(
            dashboardOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardOptionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(dashboardIcon)
                .addGap(27, 27, 27)
                .addComponent(dashboardText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardOptionLayout.setVerticalGroup(
            dashboardOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardOptionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dashboardText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(dashboardIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        catatOption.setBackground(new java.awt.Color(33, 25, 81));
        catatOption.setForeground(new java.awt.Color(255, 255, 255));

        catatText.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        catatText.setForeground(new java.awt.Color(166, 163, 185));
        catatText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catatText.setText("Catat Transaksi");

        catatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 5(1).png"))); // NOI18N

        javax.swing.GroupLayout catatOptionLayout = new javax.swing.GroupLayout(catatOption);
        catatOption.setLayout(catatOptionLayout);
        catatOptionLayout.setHorizontalGroup(
            catatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catatOptionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(catatIcon)
                .addGap(27, 27, 27)
                .addComponent(catatText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        catatOptionLayout.setVerticalGroup(
            catatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catatIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(catatText, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        laporanOption.setBackground(new java.awt.Color(55, 48, 98));
        laporanOption.setForeground(new java.awt.Color(255, 255, 255));

        laporanText.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        laporanText.setForeground(new java.awt.Color(255, 255, 255));
        laporanText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laporanText.setText("Laporan");

        laporanIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 5(2).png"))); // NOI18N

        javax.swing.GroupLayout laporanOptionLayout = new javax.swing.GroupLayout(laporanOption);
        laporanOption.setLayout(laporanOptionLayout);
        laporanOptionLayout.setHorizontalGroup(
            laporanOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanOptionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(laporanIcon)
                .addGap(27, 27, 27)
                .addComponent(laporanText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        laporanOptionLayout.setVerticalGroup(
            laporanOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laporanIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporanText, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        riwayatOption.setBackground(new java.awt.Color(33, 25, 81));
        riwayatOption.setForeground(new java.awt.Color(255, 255, 255));

        riwayatText.setBackground(new java.awt.Color(166, 163, 185));
        riwayatText.setFont(new java.awt.Font("PT Sans", 0, 16)); // NOI18N
        riwayatText.setForeground(new java.awt.Color(166, 163, 185));
        riwayatText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        riwayatText.setText("Riwayat Transaksi");
        riwayatText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatTextMouseClicked(evt);
            }
        });

        riwayatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 5.png"))); // NOI18N

        javax.swing.GroupLayout riwayatOptionLayout = new javax.swing.GroupLayout(riwayatOption);
        riwayatOption.setLayout(riwayatOptionLayout);
        riwayatOptionLayout.setHorizontalGroup(
            riwayatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, riwayatOptionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(riwayatIcon)
                .addGap(27, 27, 27)
                .addComponent(riwayatText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        riwayatOptionLayout.setVerticalGroup(
            riwayatOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(riwayatText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(riwayatIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        logout.setBackground(new java.awt.Color(55, 48, 98));

        userPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Ellipse 1.png"))); // NOI18N
        userPhoto.setText(" ");

        username.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Sutha");

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finansaku/assets/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(userPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutIcon)
                .addGap(21, 21, 21))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(userPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout SidebarLayout = new javax.swing.GroupLayout(Sidebar);
        Sidebar.setLayout(SidebarLayout);
        SidebarLayout.setHorizontalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(riwayatOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidebarLayout.createSequentialGroup()
                .addGroup(SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SidebarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SidebarLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(catatOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporanOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidebarLayout.setVerticalGroup(
            SidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidebarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(dashboardOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(riwayatOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catatOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 770));

        setSize(new java.awt.Dimension(1382, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void riwayatTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatTextMouseClicked

    private void riwayat1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_riwayat1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayat1ComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanSaku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanSaku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JLabel catatIcon;
    private javax.swing.JPanel catatOption;
    private javax.swing.JLabel catatText;
    private javax.swing.JPanel cetakButton;
    private javax.swing.JLabel cetakText;
    private javax.swing.JLabel dashboardIcon;
    private javax.swing.JPanel dashboardOption;
    private javax.swing.JLabel dashboardText;
    private javax.swing.JPanel editContainer;
    private javax.swing.JPanel editContainer19;
    private javax.swing.JLabel greetDesc;
    private javax.swing.JLabel greetText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel laporanIcon;
    private javax.swing.JPanel laporanOption;
    private javax.swing.JLabel laporanText;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JPanel mainContent;
    private javax.swing.JLabel riwayat1;
    private javax.swing.JLabel riwayatIcon;
    private javax.swing.JPanel riwayatOption;
    private javax.swing.JLabel riwayatText;
    private javax.swing.JScrollPane tableContainer;
    private javax.swing.JLabel totalKeluarNumber;
    private javax.swing.JLabel totalKeluarText;
    private javax.swing.JLabel totalMasukNumber;
    private javax.swing.JLabel totalMasukText;
    private javax.swing.JLabel totalTsNumber;
    private javax.swing.JLabel totalTsText;
    private javax.swing.JTable transaksiTable;
    private javax.swing.JLabel userPhoto;
    private javax.swing.JLabel username;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
